- name: installing pacakages
  hosts: target
  task:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start services
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes